pwa:
    asset_compiler: false
    image_processor: 'imagick' # Or 'gd'
    #logger: 'App\Service\PwaLogger'
    #native:
    #    enabled: true
    #    user_agent: 'Google Chrome'
    #    header_name: 'sec-ch-ua'
    favicons:
        enabled: true
        default:
            src: "images/pwabundlelogo.svg"
            background_color: "#FCFCFC"
        dark:
            src: "images/pwabundlelogo-dark.svg"
            background_color: "#121212"
        tile_color: "#FCFCFC"
        use_start_image: true
        use_silhouette: true
        safari_pinned_tab_color: "#FCFCFC"
        low_resolution: true
        #monochrome: true
        potrace: "potrace"
    manifest:
        enabled: true
        public_url: '/site.{locale}.webmanifest'
        background_color: "#FCFCFC"
        theme_color: "#BE202F"
        dark_theme_color: "#EF4444"
        name: 'app.name'
        short_name: 'app.short_name'
        description: 'app.description'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        dir: 'ltr'
        id: "pwa-bundle-today"
        start_url:
            path: 'app_homepage'
            params:
                pwa: 1
        icons:
            - src: "images/pwabundlelogo.svg"
              format: 'png'
              sizes: [48, 96, 128, 144, 192, 256, 384, 512]
              purpose: 'any'
            - src: "images/pwabundlelogo.svg"
              format: 'png'
              sizes: [48, 96, 128, 144, 192, 256, 384, 512]
              image_scale: 50
              background_color: "#c3d7f7"
              purpose: 'maskable'
        screenshots:
            - src: "images/wide.png"
              format: 'png'
              label: "The homepage"
            - src: "images/narrow.png"
              format: 'png'
              label: "The homepage"
        categories:
            - "education"
            - "utilities"
        shortcuts:
            - name: "app.features.geolocation.name"
              short_name: "app.features.geolocation.short_name"
              description: "app.features.geolocation.description"
              url: 'app_feature_geolocation'
              icons:
                  - src: "mdi:location"
                    sizes: [48, 96, 128, 144, 192, 256, 384, 512]
                    format: 'png'
                    svg_attr:
                        color: '#0F0'
                        fill: '#0F0'
                        stroke: '#0F0'
            - name: "app.features.geolocation.name"
              short_name: "app.features.geolocation.short_name"
              description: "app.features.geolocation.description"
              url: 'app_feature_geolocation'
              icons:
                  - src: "logos:pwa"
                    sizes: [48, 96, 128, 144, 192, 256, 384, 512]
                    format: 'png'
                    svg_attr:
                        color: '#F00'
                        fill: '#F00'
                        stroke: '#F00'
        launch_handler:
            client_mode: ['focus-existing', 'auto']
        edge_side_panel:
            preferred_width: 280
        widgets: []
        related_applications: []
        file_handlers:
            - action: "app_feature_file_handling"
              accept:
                  "image/png": [".png"]
                  "image/jpeg": [".jpg", ".jpeg"]
                  "image/webm": [".webm"]
        share_target:
            action: "app_feature_share_target"
            method: "POST"
            enctype: "multipart/form-data"
            params:
                title: 'title'
                text: 'text'
                url: 'link'
                files:
                    - name: 'file'
                      accept: [
                          "image/*",
                          "image/jpeg",
                          "image/png",
                          "image/webp",
                          ".jpg",
                          ".jpeg",
                          ".png",
                          ".webp"
                      ]
        handle_links: "preferred"
        protocol_handlers:
            - protocol: "web+pwabundle"
              placeholder: 'type'
              url:
                  path: "app_protocol_handler"

    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: false
        workbox:
            enabled: true
            offline_fallback:
                page:
                    path: 'app_homepage'
                    params:
                        _locale: 'en'
            resource_caches:
                - match_callback: 'startsWith: /videos/'
                  cache_name: 'videos'
                  strategy: 'CacheFirst'
                - match_callback: 'navigate'
                  cache_name: 'pages'
                  strategy: 'NetworkFirst'
                  network_timeout: 2
                  preload_urls:
                      - '@pages'
            background_sync:
                - queue_name: 'form'
                  match_callback: 'startsWith: /form'
                  method: POST
                  max_retention_time: 7_200 # 5 days in minutes
                  force_sync_fallback: true #Optional
                  broadcast_channel: 'form-list'
            background_fetch:
                enabled: true
    #            success_message: 'Your download is ready!'
    #            failure_message: 'Your download failed! Please try again.'
