pwa:
    image_processor: 'pwa.image_processor.imagick'
    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'Simple TODO App'
        short_name: 'Todo App'
        description: 'A simple TODO application build using Symfony and PHPWA'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: "/"
        icons:
            - src: "images/todo.svg"
              sizes: "any"
        screenshots:
            - "images/screenshot1.png"
            - "images/screenshot2.png"
        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
        related_applications:
            - platform: "webapp"
              url: "https://localhost/site.webmanifest"
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            page_cache:
                urls:
                - 'app_homepage'
                - '_api_/items{._format}_get_collection'
            offline_fallback:
                page: 'app_homepage'
            background_sync:
                - queue_name: 'sync-queue'
                  regex: 'https://localhost\\:8000(\/|\/items\/.*)$'
                  max_retention_time: 7200
                  force_sync_fallback: false
