name: 🐛 Rapport de bug
description: ⚠️ NE JAMAIS signaler de problème de sécurité ici, envoyez plutôt un email à security AT spomky-labs.com
labels: Bug
body:
    - type: input
      id: affected-versions
      attributes:
          label: Version(s) concernée(s)
          placeholder: x.y.z
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Une description claire et concise du problème
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: Comment reproduire
          description: |
              ⚠️  C’est la partie la plus importante du rapport ⚠️
              Sans un moyen simple de reproduire votre problème, il y a peu de chances que nous puissions vous aider et travailler sur un correctif.
              Prenez le temps de nous montrer un bout de code et/ou de configuration nécessaire pour que d’autres puissent reproduire facilement le problème.
              La plupart du temps, créer un "reproducteur de bug" est la meilleure manière de nous aider et augmente les chances
              qu’une personne y jette un œil.
      validations:
          required: true
    - type: textarea
      id: possible-solution
      attributes:
          label: Solution possible
          description: |
              Optionnel : uniquement si vous avez des suggestions sur un correctif ou la cause du bug
              N’hésitez pas à créer une pull request avec votre solution, cela permet d’obtenir un retour plus rapidement.
    - type: textarea
      id: additional-context
      attributes:
          label: Contexte additionnel
          description: "Optionnel : tout autre contexte lié au problème : messages de log, captures d’écran, etc."
