name: 🚀 Demande de fonctionnalité
description: RFC et idées pour de nouvelles fonctionnalités et améliorations
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Une description claire et concise de la nouvelle fonctionnalité
      validations:
          required: true
    - type: textarea
      id: example
      attributes:
          label: Exemple
          description: |
              Un exemple simple de la nouvelle fonctionnalité en action (inclure du code PHP, une configuration YAML, etc.)
              Si la nouvelle fonctionnalité modifie une fonctionnalité existante, inclure une comparaison simple avant/après.
