name: 📖 Problème de documentation
description: Pour signaler une faute de frappe ou une section obsolète dans la documentation
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Une description claire et concise de l’erreur que vous avez trouvée dans la documentation
      validations:
          required: true
