blank_issues_enabled: false
contact_links:
    - name: Question de support
      url: https://spomky-labs.com/contact/
      about: |
          Nous utilisons GitHub Issues uniquement pour discuter des bugs et des nouvelles fonctionnalités.
          Pour ce type de questions concernant l’utilisation du framework ou de bundles tiers,
          veuillez nous contacter par email à contact AT spomky-labs.com pour une demande de devis.
